### ISSUE TITLE
yolov5x,yolov5s weights on COCO 

### ISSUE THREAD

**Issue by jamjamjon** [Jacobi93/Alpha-IoU#1]

**Comment by jamjamjon** [comment]
would you mind upload yolov5s, yolov5x weights trained on COCO? Thx.

**Comment by Jacobi93** [comment]
Thx so much for your interest in our repo. We did experiments on COCO with YOLOv5 version 3.0 (https://github.com/ultralytics/yolov5/releases), which is different from this repo, i.e., YOLOv5 version 4.0. YOLOv5 has been updated for many versions. Plz re-train them using either this repo or apply our method to the latest version of YOLOv5 (https://github.com/ultralytics/yolov5). You should obtain close results. Thx.
