### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by yxx-byte** [Jacobi93/Alpha-IoU#11]

**Comment by yxx-byte** [comment]
可以具体说说嘛

**Comment by Jacobi93** [comment]
感谢关注，请看：
### Alpha-IoU Losses

Alpha-IoU losses can be configured in Line 131 of [utils/loss.py](https://github.com/Jacobi93/Alpha-IoU/blob/main/utils/loss.py), functionesd as 'bbox_alpha_iou'. The alpha values and types of losses (e.g., IoU, GIoU, DIoU, CIoU) can be selected in this function, which are defined in [utils/general.py](https://github.com/Jacobi93/Alpha-IoU/blob/main/utils/general.py). Note that we should use a small constant epsilon to **avoid torch.pow(0, alpha) or denominator=0**.
