### ISSUE TITLE
question

### ISSUE THREAD

**Issue by weizhao-11** [Jacobi93/Alpha-IoU#5]
Yolov5's original loss function is ciou. When a = 3, the accuracy of using a-ciou will decrease by 1.2%. Is it true that a-ciou is not as effective as ciou?

**Comment by Jacobi93** [comment]
Thx so much for your interest. We obtain consistent and noticeable improvement when alpha is in [2, 3] of alpha-ciou, using YOLOv5s on both PASCAL VOC and COCO.

**Comment by weizhao-11** [comment]
Is the improvement compared with yolov5s ciou？

**Comment by Jacobi93** [comment]
Yep, that's right.

**Comment by weizhao-11** [comment]
Because I didn't see the comparison with ciou in the paper, do I have any doubts, so I want to ask you. Thank you very much for your answer.

**Comment by Jacobi93** [comment]
No worries.
