### ISSUE TITLE
Hello, may I ask why I meet the problem of inaccurate classification when I reproduce various IOU without α

### ISSUE THREAD

**Issue by dandervis** [Jacobi93/Alpha-IoU#7]
Hello, may I ask why I meet the problem of inaccurate classification when I reproduce various IOU without α

**Comment by Jacobi93** [comment]
hi, thx for your interest. do you mean that you try to reproduce baseline results (alpha=1) but get worse results?

**Comment by dandervis** [comment]
Thank you for taking the time to reply. Yes, when I reproduced the bbox_iou function (iou = inter/union, which means alpha=1) in the open source code in your paper, the accuracy was extremely poor. Could you please tell me what went wrong?

**Comment by Jacobi93** [comment]
plz try the function 'bbox_iou' (https://github.com/Jacobi93/Alpha-IoU/blob/main/utils/general.py) without alpha, which is exactly the same as 'bbox_iou' in the original project YOLOv5 (https://github.com/ultralytics/yolov5). You only need to choose loss types (e.g., GIoU, DIoU or CIoU) in this function without setting alpha=1. Then you should be able to obtain reasonable results. thx.

**Comment by dandervis** [comment]
thx very much
